/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;
import model.Fornecedor;
import controller.FornecedorDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author joelmir
 */
public class ConsultarFornecedor extends javax.swing.JInternalFrame {
    FornecedorDao fdao = new FornecedorDao();
    /**
     * Creates new form Consultar
     */
    public ConsultarFornecedor() {
        initComponents();
          //Comando para centralizar janela
        // Obtém as dimensões da tela
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcula a posição para centralizar a janela
        int x = (screenSize.width - getWidth()) / 2;
        int y = (screenSize.height - getHeight()) / 2;

        // Define a posição da janela
        setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_titulo = new javax.swing.JLabel();
        jLabel_nome = new javax.swing.JLabel();
        jTextField_nomeFornecedor_ = new javax.swing.JTextField();
        jButton_buscar_ = new javax.swing.JButton();
        jButton_sair_ = new javax.swing.JButton();
        jButton_limpar_ = new javax.swing.JButton();
        jButton_buscaCompleta_ = new javax.swing.JButton();
        jButton_atualizar_ = new javax.swing.JButton();
        jButton_excluir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_fornecedor = new javax.swing.JTable();
        jTextField_setarCodigo = new javax.swing.JTextField();
        jTextField_setarNome = new javax.swing.JTextField();
        jTextField_setarCnpj = new javax.swing.JTextField();
        jTextField_setarEmail = new javax.swing.JTextField();
        jTextField_setarTelefone = new javax.swing.JTextField();
        jTextField_setarEndereco = new javax.swing.JTextField();
        jTextField_setarPoduto = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta Fornecedor");

        jLabel_titulo.setText("Consultar Fornecedor:");

        jLabel_nome.setText("Nome Fornecedor:");

        jButton_buscar_.setText("Buscar");
        jButton_buscar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscar_ActionPerformed(evt);
            }
        });

        jButton_sair_.setText("Sair");
        jButton_sair_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sair_ActionPerformed(evt);
            }
        });

        jButton_limpar_.setText("Limpar");
        jButton_limpar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limpar_ActionPerformed(evt);
            }
        });

        jButton_buscaCompleta_.setText("Busca Completa");
        jButton_buscaCompleta_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscaCompleta_ActionPerformed(evt);
            }
        });

        jButton_atualizar_.setText("Ataulizar");
        jButton_atualizar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_atualizar_ActionPerformed(evt);
            }
        });

        jButton_excluir.setText("Excluir");
        jButton_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                                .addComponent(jTextField_nomeFornecedor_, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_titulo))
                        .addGap(52, 52, 52))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jButton_buscar_, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(232, 232, 232)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_limpar_))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_atualizar_)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_sair_)
                        .addGap(36, 36, 36)
                        .addComponent(jButton_buscaCompleta_, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(112, 112, 112))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_sair_, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_buscaCompleta_, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_atualizar_, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_limpar_, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nome)
                    .addComponent(jTextField_nomeFornecedor_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton_buscar_, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTable_fornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "CNPJ", "Email", "Telefone", "Endereco", "Produto"
            }
        ));
        jTable_fornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_fornecedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_fornecedor);

        jTextField_setarCodigo.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jTextField_setarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_setarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_setarCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_setarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_setarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_setarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_setarPoduto))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_setarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_setarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_setarCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_setarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_setarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_setarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_setarPoduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(85, 85, 85))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_buscar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscar_ActionPerformed
        // TODO add your handling code here:
        this.Buscar();
    }//GEN-LAST:event_jButton_buscar_ActionPerformed

    private void jButton_sair_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sair_ActionPerformed
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_jButton_sair_ActionPerformed

    private void jButton_limpar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limpar_ActionPerformed
        // TODO add your handling code here:
        this.Limpar();
    }//GEN-LAST:event_jButton_limpar_ActionPerformed

    private void jButton_buscaCompleta_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscaCompleta_ActionPerformed
        // TODO add your handling code here:
      this.ProcurarTudo();
    }//GEN-LAST:event_jButton_buscaCompleta_ActionPerformed

    private void jButton_atualizar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_atualizar_ActionPerformed
        // TODO add your handling code here:
        this.Alterar();
    }//GEN-LAST:event_jButton_atualizar_ActionPerformed

    private void jButton_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_excluirActionPerformed
        // TODO add your handling code here:
        this.Excluir();
    }//GEN-LAST:event_jButton_excluirActionPerformed

    private void jTable_fornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_fornecedorMouseClicked
        // TODO add your handling code here:
        this.SetarLinha();
    }//GEN-LAST:event_jTable_fornecedorMouseClicked
    
    public void Limpar(){
        jTextField_nomeFornecedor_.setText("");
         
        jTextField_setarCodigo.setText("");
        jTextField_setarNome.setText("");
        jTextField_setarCnpj.setText("");
        jTextField_setarEmail.setText("");
        jTextField_setarTelefone.setText("");
        jTextField_setarEndereco.setText("");
        jTextField_setarPoduto.setText("");
    }
    
    public void Buscar(){
        Fornecedor f = new Fornecedor();
        ArrayList<Fornecedor> listaFo = new ArrayList<>();
        //criar um modelo de tabela
        DefaultTableModel taFornecedor = (DefaultTableModel) jTable_fornecedor.getModel();
        taFornecedor.setNumRows(0);
        
        listaFo = fdao.Buscar(jTextField_nomeFornecedor_.getText());
        
        Object colunas[] = new Object[7];
        for(int i=0;i<listaFo.size();i++){
            f = listaFo.get(i);
            colunas[0] = f.getCodigo();
            colunas[1] = f.getNome();
            colunas[2] = f.getCnpj();
            colunas[3] = f.getEmail();
            colunas[4] = f.getTelefone();
            colunas[5] = f.getProduto();
            colunas[6] = f.getEndereco();
            taFornecedor.addRow(colunas);
        }
    }
    
    public void ProcurarTudo(){
        Fornecedor f = new Fornecedor();
        ArrayList<Fornecedor> listaFo = new ArrayList<>();
        //criar um modelo de tabela
        DefaultTableModel taFornecedor = (DefaultTableModel) jTable_fornecedor.getModel();
        taFornecedor.setNumRows(0);
        
        listaFo = fdao.ProcurarTudo();
        
        Object colunas[] = new Object[7];
        for(int i=0;i<listaFo.size();i++){
            f = listaFo.get(i);
            colunas[0] = f.getCodigo();
            colunas[1] = f.getNome();
            colunas[2] = f.getCnpj();
            colunas[3] = f.getEmail();
            colunas[4] = f.getTelefone();
            colunas[5] = f.getProduto();
            colunas[6] = f.getEndereco();
            taFornecedor.addRow(colunas);
        }
    }
    
    public void SetarLinha(){
        
        int setar = jTable_fornecedor.getSelectedRow();
        jTextField_setarCodigo.setText(jTable_fornecedor.getModel().getValueAt(setar,0).toString());
        jTextField_setarNome.setText(jTable_fornecedor.getModel().getValueAt(setar,1).toString());
        jTextField_setarCnpj.setText(jTable_fornecedor.getModel().getValueAt(setar,2).toString());
        jTextField_setarEmail.setText(jTable_fornecedor.getModel().getValueAt(setar,3).toString());
        jTextField_setarTelefone.setText(jTable_fornecedor.getModel().getValueAt(setar,4).toString());
        jTextField_setarEndereco.setText(jTable_fornecedor.getModel().getValueAt(setar,5).toString());
        jTextField_setarPoduto.setText(jTable_fornecedor.getModel().getValueAt(setar,6).toString());
        
    }
   
    public void Alterar(){
        
        Fornecedor f = new Fornecedor();
            f.setNome(jTextField_setarNome.getText());
            f.setCnpj(jTextField_setarCnpj.getText());
            f.setEmail(jTextField_setarEmail.getText());
            f.setTelefone(jTextField_setarTelefone.getText());
            f.setProduto(jTextField_setarPoduto.getText());
            f.setEndereco(jTextField_setarEndereco.getText());
            f.setCodigo(jTextField_setarCodigo.getText());
            
        fdao.atualizar(f);
        
        int i = jTable_fornecedor.getSelectedRow();
        DefaultTableModel taFornecedor = (DefaultTableModel) jTable_fornecedor.getModel();
        
        if(i >= 0){
            
            taFornecedor.setValueAt(jTextField_setarCodigo.getText(), i, 0);
            taFornecedor.setValueAt(jTextField_setarNome.getText(), i, 1);
            taFornecedor.setValueAt(jTextField_setarCnpj.getText(), i, 2);
            taFornecedor.setValueAt(jTextField_setarEmail.getText(), i, 3);
            taFornecedor.setValueAt(jTextField_setarTelefone.getText(), i, 4);
            taFornecedor.setValueAt(jTextField_setarPoduto.getText(), i, 5);
            taFornecedor.setValueAt(jTextField_setarEndereco.getText(), i, 6);
            
            JOptionPane.showMessageDialog(null,"Realizado Atualização!");
           
            this.Limpar();
            
        }else{
            JOptionPane.showMessageDialog(null,"Erro Atualização");
        }
            
    }
    
     public void Excluir() {
        
        int i = jTable_fornecedor.getSelectedRow();
        
        int f = Integer.parseInt(jTextField_setarCodigo.getText());
        
        fdao.excluir(f);
        
        if(i >= 0){
            DefaultTableModel taFun = (DefaultTableModel) jTable_fornecedor.getModel();
            taFun.setNumRows(i);
        
            JOptionPane.showMessageDialog(null,"Item Excluido!");
           
             this.Limpar();
        
        }else{
            JOptionPane.showMessageDialog(null,"Erro ao Excluir!\nSelesione Item!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_atualizar_;
    private javax.swing.JButton jButton_buscaCompleta_;
    private javax.swing.JButton jButton_buscar_;
    private javax.swing.JButton jButton_excluir;
    private javax.swing.JButton jButton_limpar_;
    private javax.swing.JButton jButton_sair_;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_fornecedor;
    private javax.swing.JTextField jTextField_nomeFornecedor_;
    private javax.swing.JTextField jTextField_setarCnpj;
    private javax.swing.JTextField jTextField_setarCodigo;
    private javax.swing.JTextField jTextField_setarEmail;
    private javax.swing.JTextField jTextField_setarEndereco;
    private javax.swing.JTextField jTextField_setarNome;
    private javax.swing.JTextField jTextField_setarPoduto;
    private javax.swing.JTextField jTextField_setarTelefone;
    // End of variables declaration//GEN-END:variables
}
