/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.ProdutoDao;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produto;

/**
 *
 * @author joelmir
 */
public class ConsultarProduto extends javax.swing.JInternalFrame {
     ProdutoDao pdao = new ProdutoDao();
    /**
     * Creates new form Consultar
     */
    public ConsultarProduto() {
       
        initComponents();
          //Comando para centralizar janela
        // Obtém as dimensões da tela
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcula a posição para centralizar a janela
        int x = (screenSize.width - getWidth()) / 2;
        int y = (screenSize.height - getHeight()) / 2;

        // Define a posição da janela
        setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_titulo = new javax.swing.JLabel();
        jLabel_nome = new javax.swing.JLabel();
        jTextField_nomeProduto_ = new javax.swing.JTextField();
        jButton_buscar_ = new javax.swing.JButton();
        jButton_sair_ = new javax.swing.JButton();
        jButton_limpar_ = new javax.swing.JButton();
        jButton_buscaCompleta_ = new javax.swing.JButton();
        jButton_alterar_ = new javax.swing.JButton();
        jButton_excluir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_produto = new javax.swing.JTable();
        jTextField_setarCodigo = new javax.swing.JTextField();
        jTextField_setarNome = new javax.swing.JTextField();
        jTextField_setarPreco = new javax.swing.JTextField();
        jTextField_setarQuantidade = new javax.swing.JTextField();
        jTextField_setarDescriçao = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Produtos");

        jLabel_titulo.setText("Consultar Produto:");

        jLabel_nome.setText("Nome Produto:");

        jTextField_nomeProduto_.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_nomeProduto_KeyReleased(evt);
            }
        });

        jButton_buscar_.setText("Buscar");
        jButton_buscar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscar_ActionPerformed(evt);
            }
        });

        jButton_sair_.setText("Sair");
        jButton_sair_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sair_ActionPerformed(evt);
            }
        });

        jButton_limpar_.setText("Limpar");
        jButton_limpar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limpar_ActionPerformed(evt);
            }
        });

        jButton_buscaCompleta_.setText("Busca Completa");
        jButton_buscaCompleta_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscaCompleta_ActionPerformed(evt);
            }
        });

        jButton_alterar_.setText("Alterar");
        jButton_alterar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_alterar_ActionPerformed(evt);
            }
        });

        jButton_excluir.setText("Excluir");
        jButton_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(jTextField_nomeProduto_, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jButton_buscar_, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_limpar_))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_alterar_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_sair_)))
                .addGap(93, 93, 93)
                .addComponent(jButton_buscaCompleta_, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel_titulo)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_nomeProduto_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_nome))
                                .addGap(18, 18, 18)
                                .addComponent(jButton_buscar_, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_alterar_, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_sair_, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_limpar_, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton_buscaCompleta_, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTable_produto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Preco", "Quantidade", "Descrição"
            }
        ));
        jTable_produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_produtoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_produto);

        jTextField_setarCodigo.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
                .addGap(50, 50, 50))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_setarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_setarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_setarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_setarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_setarDescriçao, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_setarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_setarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_setarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_setarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_setarDescriçao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(50, 50, 50)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_buscar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscar_ActionPerformed
        this.Buscar();
    }//GEN-LAST:event_jButton_buscar_ActionPerformed

    private void jButton_sair_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sair_ActionPerformed
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_jButton_sair_ActionPerformed

    private void jButton_limpar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limpar_ActionPerformed
        // TODO add your handling code here:
       this.Limpar();
    }//GEN-LAST:event_jButton_limpar_ActionPerformed

    private void jButton_buscaCompleta_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscaCompleta_ActionPerformed
        // TODO add your handling code here:
        this.ProcurarTudo();
    }//GEN-LAST:event_jButton_buscaCompleta_ActionPerformed

    private void jButton_alterar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_alterar_ActionPerformed
        // TODO add your handling code here:
       this.Alterar();
      
    }//GEN-LAST:event_jButton_alterar_ActionPerformed

    private void jButton_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_excluirActionPerformed
        // TODO add your handling code here:
        this.Excluir();
    }//GEN-LAST:event_jButton_excluirActionPerformed

    private void jTextField_nomeProduto_KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nomeProduto_KeyReleased
    }//GEN-LAST:event_jTextField_nomeProduto_KeyReleased

    private void jTable_produtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_produtoMouseClicked
       //Evento usado para setar campos da tabela
       this.SetarLinha();
    }//GEN-LAST:event_jTable_produtoMouseClicked
            
    public void Limpar(){
        
        jTextField_nomeProduto_.setText("");
         
        jTextField_setarNome.setText("");
        jTextField_setarPreco.setText("");
        jTextField_setarQuantidade.setText("");
        jTextField_setarDescriçao.setText("");
        jTextField_setarCodigo.setText("");
        
    }
    
    
    public void Buscar(){
        Produto p = new Produto();
        ArrayList<Produto> listaP = new ArrayList<>();
        //criar um modelo de tabela
        DefaultTableModel taProduto = (DefaultTableModel) jTable_produto.getModel();
        taProduto.setNumRows(0);
        
        listaP = pdao.Buscar(jTextField_nomeProduto_.getText());
        
        Object colunas[] = new Object[5];
        for(int i=0; i<listaP.size();i++){
            p = listaP.get(i);
            colunas[0] = p.getCodigo();
            colunas[1] = p.getNome();
            colunas[2] = p.getPreco();
            colunas[3] = p.getQuantidade();
            colunas[4] = p.getDescricao();
            
            taProduto.addRow(colunas);
        }
    }
    
    public void ProcurarTudo(){
        Produto p = new Produto();
        ArrayList<Produto> listaP = new ArrayList<>();
        //criar um modelo de tabela
        DefaultTableModel taProduto = (DefaultTableModel) jTable_produto.getModel();
        taProduto.setNumRows(0);
        
        listaP = (ArrayList<Produto>) pdao.ProcurarTudo();
        
        Object colunas[] = new Object[5];
        for(int i=0; i<listaP.size();i++){
            p = listaP.get(i);
            
            colunas[0] = p.getCodigo();
            colunas[1] = p.getNome();
            colunas[2] = p.getPreco();
            colunas[3] = p.getQuantidade();
            colunas[4] = p.getDescricao();
            
            taProduto.addRow(colunas);
        }
    }
    
    public void SetarLinha(){
        int setar = jTable_produto.getSelectedRow();
        jTextField_setarCodigo.setText( jTable_produto.getModel().getValueAt(setar,0).toString());
        jTextField_setarNome.setText( jTable_produto.getModel().getValueAt(setar,1).toString());
        jTextField_setarPreco.setText(jTable_produto.getModel().getValueAt(setar,2).toString());
        jTextField_setarQuantidade.setText( jTable_produto.getModel().getValueAt(setar,3).toString());
        jTextField_setarDescriçao.setText( jTable_produto.getModel().getValueAt(setar, 4).toString());
    }
    
    public void Alterar(){
        
        Produto p = new Produto();
            p.setNome(jTextField_setarNome.getText());
            p.setPreco(Float.parseFloat(jTextField_setarPreco.getText()));
            p.setQuantidade(Integer.parseInt(jTextField_setarQuantidade.getText()));
            p.setDescricao(jTextField_setarDescriçao.getText());
            p.setCodigo(jTextField_setarCodigo.getText());
           
        // Enviar os parâmetros para a classe Atualizar
        pdao.atualizar(p);
 
        int i = jTable_produto.getSelectedRow();
        DefaultTableModel taProduto = (DefaultTableModel) jTable_produto.getModel();
        
        if(i >= 0){
            
            taProduto.setValueAt(jTextField_setarCodigo.getText(), i,0);
            taProduto.setValueAt(jTextField_setarNome.getText(), i, 1);
            taProduto.setValueAt(jTextField_setarPreco.getText(), i, 2);
            taProduto.setValueAt(jTextField_setarQuantidade.getText(), i, 3);
            taProduto.setValueAt(jTextField_setarDescriçao.getText(), i, 4);
            
            JOptionPane.showMessageDialog(null,"Realizado Atualização!");
           
            this.Limpar();
            
        }else{
            JOptionPane.showMessageDialog(null,"Erro Atualização");
        }
        
    }
    
    public void Excluir(){
        
        int i = jTable_produto.getSelectedRow();
           
        int p = Integer.parseInt(jTextField_setarCodigo.getText());
            
        pdao.excluir(p);
            
        if(i >= 0){
           
        DefaultTableModel taProduto = (DefaultTableModel) jTable_produto.getModel();
        taProduto.removeRow(i);
        
        JOptionPane.showMessageDialog(null,"Item Excluido!");
           
        this.Limpar();
        
        }else{
            JOptionPane.showMessageDialog(null,"Erro ao Excluir!\nSelesione Item!");
        }
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_alterar_;
    private javax.swing.JButton jButton_buscaCompleta_;
    private javax.swing.JButton jButton_buscar_;
    private javax.swing.JButton jButton_excluir;
    private javax.swing.JButton jButton_limpar_;
    private javax.swing.JButton jButton_sair_;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_produto;
    private javax.swing.JTextField jTextField_nomeProduto_;
    private javax.swing.JTextField jTextField_setarCodigo;
    private javax.swing.JTextField jTextField_setarDescriçao;
    private javax.swing.JTextField jTextField_setarNome;
    private javax.swing.JTextField jTextField_setarPreco;
    private javax.swing.JTextField jTextField_setarQuantidade;
    // End of variables declaration//GEN-END:variables

}
