/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.ClienteDao;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;

/**
 *
 * @author joelmir
 */
public class ConsultarCliente extends javax.swing.JInternalFrame {
    ClienteDao cdao = new ClienteDao() {};
    /**
     * Creates new form Consultar
     */
    public ConsultarCliente() {
        initComponents();
          //Comando para centralizar janela
        // Obtém as dimensões da tela
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcula a posição para centralizar a janela
        int x = (screenSize.width - getWidth()) / 2;
        int y = (screenSize.height - getHeight()) / 2;

        // Define a posição da janela
        setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_titulo = new javax.swing.JLabel();
        jLabel_nome = new javax.swing.JLabel();
        jTextField_nomecliente_ = new javax.swing.JTextField();
        jButton_Buscar_ = new javax.swing.JButton();
        jButton_sair_ = new javax.swing.JButton();
        jButton_limpar_ = new javax.swing.JButton();
        jButton_BuscaCompleta_ = new javax.swing.JButton();
        jButton_atualizar_ = new javax.swing.JButton();
        jButton_excluir = new javax.swing.JButton();
        jPanel_tabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_cliente = new javax.swing.JTable();
        jTextField_setarCodigo = new javax.swing.JTextField();
        jTextField_setarNome = new javax.swing.JTextField();
        jTextField_setarCpf = new javax.swing.JTextField();
        jTextField_setarEmail = new javax.swing.JTextField();
        jTextField_setarEndereco = new javax.swing.JTextField();
        jTextField_setarTelefone = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta Cliente");

        jLabel_titulo.setText("Consultar Cliente:");

        jLabel_nome.setText("Nome Cliente:");

        jButton_Buscar_.setText("Buscar");
        jButton_Buscar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Buscar_ActionPerformed(evt);
            }
        });

        jButton_sair_.setText("Sair");
        jButton_sair_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sair_ActionPerformed(evt);
            }
        });

        jButton_limpar_.setText("Limpar");
        jButton_limpar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limpar_ActionPerformed(evt);
            }
        });

        jButton_BuscaCompleta_.setText("Busca Completa");
        jButton_BuscaCompleta_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscaCompleta_ActionPerformed(evt);
            }
        });

        jButton_atualizar_.setText("Ataulizar");
        jButton_atualizar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_atualizar_ActionPerformed(evt);
            }
        });

        jButton_excluir.setText("Excluir");
        jButton_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel_nome)
                        .addGap(27, 27, 27)
                        .addComponent(jTextField_nomecliente_, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jButton_Buscar_, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_atualizar_)
                    .addComponent(jButton_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_sair_)
                    .addComponent(jButton_limpar_))
                .addGap(33, 33, 33)
                .addComponent(jButton_BuscaCompleta_, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel_titulo)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_nome)
                            .addComponent(jTextField_nomecliente_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_atualizar_, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_sair_, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Buscar_, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_limpar_, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton_BuscaCompleta_, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_tabelaLayout = new javax.swing.GroupLayout(jPanel_tabela);
        jPanel_tabela.setLayout(jPanel_tabelaLayout);
        jPanel_tabelaLayout.setHorizontalGroup(
            jPanel_tabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        jPanel_tabelaLayout.setVerticalGroup(
            jPanel_tabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jTable_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Email", "Telefone", "Endereco"
            }
        ));
        jTable_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_clienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_cliente);

        jTextField_setarCodigo.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(930, 930, 930)
                        .addComponent(jTextField_setarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_tabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_setarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_setarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_setarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_setarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_setarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_tabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_setarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_setarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_setarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_setarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_setarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_setarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Buscar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Buscar_ActionPerformed
        this.Buscar();
    }//GEN-LAST:event_jButton_Buscar_ActionPerformed

    private void jButton_sair_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sair_ActionPerformed
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_jButton_sair_ActionPerformed

    private void jButton_limpar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limpar_ActionPerformed
        // TODO add your handling code here:
       this.Limpar();
    }//GEN-LAST:event_jButton_limpar_ActionPerformed

    private void jButton_BuscaCompleta_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscaCompleta_ActionPerformed
        // TODO add your handling code here:
         this.ProcurarTudo();
    }//GEN-LAST:event_jButton_BuscaCompleta_ActionPerformed

    private void jButton_atualizar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_atualizar_ActionPerformed
        // TODO add your handling code here:
        this.Alterar();
    }//GEN-LAST:event_jButton_atualizar_ActionPerformed

    private void jButton_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_excluirActionPerformed
        // TODO add your handling code here:
        this.Excluir();
    }//GEN-LAST:event_jButton_excluirActionPerformed

    private void jTable_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_clienteMouseClicked
        // TODO add your handling code here:
        this.SetarLinha();
    }//GEN-LAST:event_jTable_clienteMouseClicked

    public void Limpar(){
        jTextField_nomecliente_.setText("");
         
        jTextField_setarCodigo.setText("");
        jTextField_setarNome.setText("");
        jTextField_setarCpf.setText("");
        jTextField_setarEmail.setText("");
        jTextField_setarEndereco.setText("");
    }
    
    public void Buscar(){
        
        Cliente c = new Cliente();
        ArrayList<Cliente> listC = new ArrayList<>();
        //criar um modelo de tabela
        DefaultTableModel taCli = (DefaultTableModel) jTable_cliente.getModel();
        taCli.setNumRows(0);
        
        listC = cdao.Buscar(jTextField_nomecliente_.getText());
        
        Object colunas[] = new Object[6];
        for(int i=0;i<listC.size();i++){
            c = listC.get(i);
            colunas[0] = c.getCodigo();
            colunas[1] = c.getNome();
            colunas[2] = c.getCpf();
            colunas[3] = c.getEmail();
            colunas[4] = c.getTelefone();
            colunas[5] = c.getEndereco();
            
            taCli.addRow(colunas);
        }
    }
    
    public void ProcurarTudo(){
        Cliente c = new Cliente();
        ArrayList<Cliente> listC = new ArrayList<>();
        //criar um modelo de tabela
        DefaultTableModel taCli = (DefaultTableModel) jTable_cliente.getModel();
        taCli.setNumRows(0);
        
        listC = cdao.ProcurarTudo();
        
        Object colunas[] = new Object[6];
        for(int i=0;i<listC.size();i++){
            c = listC.get(i);
            colunas[0] = c.getCodigo();
            colunas[1] = c.getNome();
            colunas[2] = c.getCpf();
            colunas[3] = c.getEmail();
            colunas[4] = c.getTelefone();
            colunas[5] = c.getEndereco();
            
            taCli.addRow(colunas);
        }
    }
    
    public void SetarLinha(){
        
        int setar = jTable_cliente.getSelectedRow();
        jTextField_setarCodigo.setText(jTable_cliente.getModel().getValueAt(setar,0).toString());
        jTextField_setarNome.setText(jTable_cliente.getModel().getValueAt(setar,1).toString());
        jTextField_setarCpf.setText(jTable_cliente.getModel().getValueAt(setar,2).toString());
        jTextField_setarEmail.setText(jTable_cliente.getModel().getValueAt(setar,3).toString());
        jTextField_setarEndereco.setText(jTable_cliente.getModel().getValueAt(setar,4).toString());
    }
   
    public void Alterar(){
        
        Cliente c = new Cliente();
            c.setCodigo(jTextField_setarCodigo.getText());
            c.setNome(jTextField_setarNome.getText());
            c.setCpf(jTextField_setarCpf.getText());
            c.setEmail(jTextField_setarEmail.getText());
            c.setTelefone(jTextField_setarTelefone.getText());
            c.setEndereco(jTextField_setarEndereco.getText());
        cdao.atualizar(c);
        
        int i = jTable_cliente.getSelectedRow();
        DefaultTableModel taCli = (DefaultTableModel) jTable_cliente.getModel();
        if(i >= 0){
            
            taCli.setValueAt(jTextField_setarCodigo.getText(), i, 0);
            taCli.setValueAt(jTextField_setarNome.getText(), i, 1);
            taCli.setValueAt(jTextField_setarCpf.getText(), i, 2);
            taCli.setValueAt(jTextField_setarEmail.getText(), i, 3);
            taCli.setValueAt(jTextField_setarTelefone.getText(), i, 4);
            taCli.setValueAt(jTextField_setarEndereco.getText(), i, 5);
            
            JOptionPane.showMessageDialog(null,"Realizado Atualização!");
           
            this.Limpar();
        
        }else{
            JOptionPane.showMessageDialog(null,"Erro Atualização");
        }
    
    }
   
    public void Excluir(){
        
       int i = jTable_cliente.getSelectedRow();
           
        int c = Integer.parseInt(jTextField_setarCodigo.getText());
            
        cdao.excluir(c);
            
        if(i >= 0){
           
        DefaultTableModel taProduto = (DefaultTableModel) jTable_cliente.getModel();
        taProduto.removeRow(i);
        
        JOptionPane.showMessageDialog(null,"Item Excluido!");
           
        this.Limpar();
        
        }else{
            JOptionPane.showMessageDialog(null,"Erro ao Excluir!\nSelesione Item!");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_BuscaCompleta_;
    private javax.swing.JButton jButton_Buscar_;
    private javax.swing.JButton jButton_atualizar_;
    private javax.swing.JButton jButton_excluir;
    private javax.swing.JButton jButton_limpar_;
    private javax.swing.JButton jButton_sair_;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_tabela;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_cliente;
    private javax.swing.JTextField jTextField_nomecliente_;
    private javax.swing.JTextField jTextField_setarCodigo;
    private javax.swing.JTextField jTextField_setarCpf;
    private javax.swing.JTextField jTextField_setarEmail;
    private javax.swing.JTextField jTextField_setarEndereco;
    private javax.swing.JTextField jTextField_setarNome;
    private javax.swing.JTextField jTextField_setarTelefone;
    // End of variables declaration//GEN-END:variables

   
}
