/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.FuncionarioDao;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Funcionario;

/**
 *
 * @author joelmir
 */
public class ConsultarFuncionario extends javax.swing.JInternalFrame {
    FuncionarioDao fdao = new FuncionarioDao();
    /**
     * Creates new form Consultar
     */
    public ConsultarFuncionario() {
        initComponents();
          //Comando para centralizar janela
        // Obtém as dimensões da tela
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcula a posição para centralizar a janela
        int x = (screenSize.width - getWidth()) / 2;
        int y = (screenSize.height - getHeight()) / 2;

        // Define a posição da janela
        setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_titulo = new javax.swing.JLabel();
        jLabel_nomeFuncionario = new javax.swing.JLabel();
        jTextField_nomefuncionario_ = new javax.swing.JTextField();
        jButton_buscar_ = new javax.swing.JButton();
        jButton_sair_ = new javax.swing.JButton();
        jButton_limpar_ = new javax.swing.JButton();
        jButton_buscaCompleta_ = new javax.swing.JButton();
        jButton_atualizar_ = new javax.swing.JButton();
        jButton_excluir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_funcionario = new javax.swing.JTable();
        jTextField_SetarCcodigo = new javax.swing.JTextField();
        jTextField_SetarNome = new javax.swing.JTextField();
        jTextField_setarCargo = new javax.swing.JTextField();
        jTextField_setarCpf = new javax.swing.JTextField();
        jTextField_setarEmail = new javax.swing.JTextField();
        jTextField_setarTelefone = new javax.swing.JTextField();
        jTextField_setarNivel = new javax.swing.JTextField();
        jTextField_setarEndereco = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Funcionario");

        jLabel_titulo.setText("Consultar Funcionario:");

        jLabel_nomeFuncionario.setText("Nome Funcionario:");

        jButton_buscar_.setText("Buscar");
        jButton_buscar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscar_ActionPerformed(evt);
            }
        });

        jButton_sair_.setText("Sair");
        jButton_sair_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sair_ActionPerformed(evt);
            }
        });

        jButton_limpar_.setText("Limpar");
        jButton_limpar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limpar_ActionPerformed(evt);
            }
        });

        jButton_buscaCompleta_.setText("Busca Completa");
        jButton_buscaCompleta_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscaCompleta_ActionPerformed(evt);
            }
        });

        jButton_atualizar_.setText("Ataulizar");
        jButton_atualizar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_atualizar_ActionPerformed(evt);
            }
        });

        jButton_excluir.setText("Excluir");
        jButton_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_titulo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_nomeFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_nomefuncionario_, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(80, 80, 80))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jButton_buscar_, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_atualizar_)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_sair_))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_limpar_)))
                .addGap(18, 18, 18)
                .addComponent(jButton_buscaCompleta_, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_titulo)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_nomeFuncionario)
                            .addComponent(jTextField_nomefuncionario_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_buscar_, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_sair_, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_atualizar_, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_limpar_, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jButton_buscaCompleta_, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTable_funcionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Cargo", "CPF", "Email", "Telefone", "Endereco", "Nivel"
            }
        ));
        jTable_funcionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_funcionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_funcionario);

        jTextField_SetarCcodigo.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_SetarCcodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_SetarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_setarCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_setarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_setarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_setarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_setarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_setarNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_SetarCcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_SetarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_setarCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_setarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_setarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_setarTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_setarNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_setarEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_buscar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscar_ActionPerformed
        // TODO add your handling code here:
       this.Buscar();
    }//GEN-LAST:event_jButton_buscar_ActionPerformed

    private void jButton_sair_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sair_ActionPerformed
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_jButton_sair_ActionPerformed

    private void jButton_limpar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limpar_ActionPerformed
        // TODO add your handling code here:
        this.Limpar();
    }//GEN-LAST:event_jButton_limpar_ActionPerformed

    private void jButton_buscaCompleta_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscaCompleta_ActionPerformed
        // TODO add your handling code here:
        this.ProcurarTudo();
    }//GEN-LAST:event_jButton_buscaCompleta_ActionPerformed

    private void jButton_atualizar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_atualizar_ActionPerformed
        // TODO add your handling code here:
        this.Alterar();
    }//GEN-LAST:event_jButton_atualizar_ActionPerformed

    private void jButton_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_excluirActionPerformed
        // TODO add your handling code here:
        this.Excluir();
    }//GEN-LAST:event_jButton_excluirActionPerformed

    private void jTable_funcionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_funcionarioMouseClicked
        // TODO add your handling code here:
        this.SetarLinha();
    }//GEN-LAST:event_jTable_funcionarioMouseClicked

    public void Limpar(){
        jTextField_nomefuncionario_.setText("");
        
        jTextField_SetarCcodigo.setText("");
        jTextField_SetarNome.setText("");
        jTextField_setarCargo.setText("");
        jTextField_setarCpf.setText("");
        jTextField_setarEmail.setText("");
        jTextField_setarTelefone.setText("");
        jTextField_setarEndereco.setText("");
        jTextField_setarNivel.setText("");
    }
    
    public void Buscar(){
        Funcionario f = new Funcionario();
        ArrayList<Funcionario> listaFu = new ArrayList<>();
        //criar um modelo de tabela
        DefaultTableModel taFun = (DefaultTableModel) jTable_funcionario.getModel();
        taFun.setNumRows(0);
        
        listaFu = fdao.Buscar(jTextField_nomefuncionario_.getText());
        
       Object colunas[] = new Object[8];
        for(int i=0; i<listaFu.size();i++){
            f = listaFu.get(i);
            colunas[0] = f.getCodigo();
            colunas[1] = f.getNome();
            colunas[2] = f.getCargo();
            colunas[3] = f.getCpf();
            colunas[4] = f.getEmail();
            colunas[5] = f.getTelefone();
            colunas[6] = f.getEndereco();
            colunas[7] = f.getNivelAscesso();
            taFun.addRow(colunas);
        }
    }
    
    public void ProcurarTudo(){
        Funcionario f = new Funcionario();
        ArrayList<Funcionario> listaFu = new ArrayList<>();
        //criar um modelo de tabela
        DefaultTableModel taFun = (DefaultTableModel) jTable_funcionario.getModel();
        taFun.setNumRows(0);
        
        listaFu = fdao.ProcurarTudo();
        
        Object colunas[] = new Object[8];
        for(int i=0; i<listaFu.size();i++){
            f = listaFu.get(i);
            colunas[0] = f.getCodigo();
            colunas[1] = f.getNome();
            colunas[2] = f.getCargo();
            colunas[3] = f.getCpf();
            colunas[4] = f.getEmail();
            colunas[5] = f.getTelefone();
            colunas[6] = f.getEndereco();
            colunas[7] = f.getNivelAscesso();
            taFun.addRow(colunas);
        }
    }

    public void SetarLinha(){
        
        int setar = jTable_funcionario.getSelectedRow();
        jTextField_SetarCcodigo.setText(jTable_funcionario.getModel().getValueAt(setar,0).toString());
        jTextField_SetarNome.setText(jTable_funcionario.getModel().getValueAt(setar,1).toString());
        jTextField_setarCargo.setText(jTable_funcionario.getModel().getValueAt(setar,2).toString());
        jTextField_setarCpf.setText(jTable_funcionario.getModel().getValueAt(setar,3).toString());
        jTextField_setarEmail.setText(jTable_funcionario.getModel().getValueAt(setar,4).toString());
        jTextField_setarTelefone.setText(jTable_funcionario.getModel().getValueAt(setar,5).toString());
        jTextField_setarEndereco.setText(jTable_funcionario.getModel().getValueAt(setar,6).toString());
        jTextField_setarNivel.setText(jTable_funcionario.getModel().getValueAt(setar,7).toString());
        
    }
    
    public void Alterar(){
        
        Funcionario f = new Funcionario();
            f.setNome(jTextField_SetarNome.getText());
            f.setCargo(jTextField_setarCargo.getText());
            f.setCpf(jTextField_setarCpf.getText());
            f.setEmail(jTextField_setarEmail.getText());
            f.setTelefone(jTextField_setarTelefone.getText());
            f.setEndereco(jTextField_setarEndereco.getText());
            f.setNivelAscesso(jTextField_setarNivel.getText());
            f.setCodigo(jTextField_SetarCcodigo.getText());
        
        fdao.atualizar(f);
        
        int i = jTable_funcionario.getSelectedRow();
        DefaultTableModel taFun = (DefaultTableModel) jTable_funcionario.getModel();
        
        if(i >= 0){
            
            taFun.setValueAt(jTextField_SetarCcodigo.getText(), i, 0);
            taFun.setValueAt(jTextField_SetarNome.getText(), i, 1);
            taFun.setValueAt(jTextField_setarCargo.getText(), i, 2);
            taFun.setValueAt(jTextField_setarCpf.getText(), i, 3);
            taFun.setValueAt(jTextField_setarEmail.getText(), i, 4);
            taFun.setValueAt(jTextField_setarTelefone.getText(), i, 5);
            taFun.setValueAt(jTextField_setarEndereco.getText(), i, 6);
            taFun.setValueAt(jTextField_setarNivel.getText(), i, 7);
            
            JOptionPane.showMessageDialog(null,"Realizado Atualização!");
           
            this.Limpar();
            
        }else{
            JOptionPane.showMessageDialog(null,"Erro Atualização");
        }
        
    }
                
    public void Excluir() {
        
        int i = jTable_funcionario.getSelectedRow();
        
        int f = Integer.parseInt(jTextField_SetarCcodigo.getText());
        
        fdao.excluir(f);
        
        if(i >= 0){
            DefaultTableModel taFun = (DefaultTableModel) jTable_funcionario.getModel();
            taFun.setNumRows(i);
        
            JOptionPane.showMessageDialog(null,"Item Excluido!");
           
             this.Limpar();
        
        }else{
            JOptionPane.showMessageDialog(null,"Erro ao Excluir!\nSelesione Item!");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_atualizar_;
    private javax.swing.JButton jButton_buscaCompleta_;
    private javax.swing.JButton jButton_buscar_;
    private javax.swing.JButton jButton_excluir;
    private javax.swing.JButton jButton_limpar_;
    private javax.swing.JButton jButton_sair_;
    private javax.swing.JLabel jLabel_nomeFuncionario;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_funcionario;
    private javax.swing.JTextField jTextField_SetarCcodigo;
    private javax.swing.JTextField jTextField_SetarNome;
    private javax.swing.JTextField jTextField_nomefuncionario_;
    private javax.swing.JTextField jTextField_setarCargo;
    private javax.swing.JTextField jTextField_setarCpf;
    private javax.swing.JTextField jTextField_setarEmail;
    private javax.swing.JTextField jTextField_setarEndereco;
    private javax.swing.JTextField jTextField_setarNivel;
    private javax.swing.JTextField jTextField_setarTelefone;
    // End of variables declaration//GEN-END:variables

    
}
