/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author joelmir
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();  
        setExtendedState(MAXIMIZED_BOTH);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_principal_ = new javax.swing.JPanel();
        jdp_principal = new javax.swing.JDesktopPane();
        jButton_produto_ = new javax.swing.JButton();
        jButton_comprar_ = new javax.swing.JButton();
        jButton_fechar_ = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_cadastrar = new javax.swing.JMenu();
        jMenuItem_cliente_ = new javax.swing.JMenuItem();
        jMenuItem_fornecedor_ = new javax.swing.JMenuItem();
        jMenuItem_funcionario = new javax.swing.JMenuItem();
        jMenu1_ConsultaProduto = new javax.swing.JMenu();
        jMenuItem_ConsultarCompra_ = new javax.swing.JMenuItem();
        jMenuItem_CobsultarCliente_ = new javax.swing.JMenuItem();
        jMenuItem_ConsultarFornecedor_ = new javax.swing.JMenuItem();
        jMenuItem_ConsultarFuncionario_ = new javax.swing.JMenuItem();
        jMenuItem_produto_ = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistemas Joelmir");

        javax.swing.GroupLayout jPanel_principal_Layout = new javax.swing.GroupLayout(jPanel_principal_);
        jPanel_principal_.setLayout(jPanel_principal_Layout);
        jPanel_principal_Layout.setHorizontalGroup(
            jPanel_principal_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1545, Short.MAX_VALUE)
        );
        jPanel_principal_Layout.setVerticalGroup(
            jPanel_principal_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jdp_principal.setBackground(java.awt.SystemColor.activeCaption);
        jdp_principal.setForeground(new java.awt.Color(51, 51, 51));
        jdp_principal.setName(""); // NOI18N

        jButton_produto_.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jButton_produto_.setText("Produto");
        jButton_produto_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_produto_ActionPerformed(evt);
            }
        });

        jButton_comprar_.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jButton_comprar_.setText("Comprar");
        jButton_comprar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_comprar_ActionPerformed(evt);
            }
        });

        jButton_fechar_.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jButton_fechar_.setText("Fechar");
        jButton_fechar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fechar_ActionPerformed(evt);
            }
        });

        jdp_principal.setLayer(jButton_produto_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_comprar_, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdp_principal.setLayer(jButton_fechar_, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdp_principalLayout = new javax.swing.GroupLayout(jdp_principal);
        jdp_principal.setLayout(jdp_principalLayout);
        jdp_principalLayout.setHorizontalGroup(
            jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdp_principalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_comprar_, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jButton_fechar_, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(jButton_produto_, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(627, 627, 627))
        );
        jdp_principalLayout.setVerticalGroup(
            jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdp_principalLayout.createSequentialGroup()
                .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jButton_fechar_, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdp_principalLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(jdp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_produto_, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_comprar_, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(797, Short.MAX_VALUE))
        );

        jMenu_cadastrar.setText("Cadastrar");
        jMenu_cadastrar.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jMenu_cadastrar.setMaximumSize(new java.awt.Dimension(150, 150));
        jMenu_cadastrar.setPreferredSize(new java.awt.Dimension(50, 50));

        jMenuItem_cliente_.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jMenuItem_cliente_.setText("Cliente");
        jMenuItem_cliente_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_cliente_ActionPerformed(evt);
            }
        });
        jMenu_cadastrar.add(jMenuItem_cliente_);

        jMenuItem_fornecedor_.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jMenuItem_fornecedor_.setText("Fornecedor");
        jMenuItem_fornecedor_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_fornecedor_ActionPerformed(evt);
            }
        });
        jMenu_cadastrar.add(jMenuItem_fornecedor_);

        jMenuItem_funcionario.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jMenuItem_funcionario.setText("Funcionario");
        jMenuItem_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_funcionarioActionPerformed(evt);
            }
        });
        jMenu_cadastrar.add(jMenuItem_funcionario);

        jMenuBar1.add(jMenu_cadastrar);

        jMenu1_ConsultaProduto.setText("Consultar");
        jMenu1_ConsultaProduto.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N

        jMenuItem_ConsultarCompra_.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jMenuItem_ConsultarCompra_.setText("Compra");
        jMenuItem_ConsultarCompra_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ConsultarCompra_ActionPerformed(evt);
            }
        });
        jMenu1_ConsultaProduto.add(jMenuItem_ConsultarCompra_);

        jMenuItem_CobsultarCliente_.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jMenuItem_CobsultarCliente_.setText("Cliente");
        jMenuItem_CobsultarCliente_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CobsultarCliente_ActionPerformed(evt);
            }
        });
        jMenu1_ConsultaProduto.add(jMenuItem_CobsultarCliente_);

        jMenuItem_ConsultarFornecedor_.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jMenuItem_ConsultarFornecedor_.setText("Fornecedor");
        jMenuItem_ConsultarFornecedor_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ConsultarFornecedor_ActionPerformed(evt);
            }
        });
        jMenu1_ConsultaProduto.add(jMenuItem_ConsultarFornecedor_);

        jMenuItem_ConsultarFuncionario_.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jMenuItem_ConsultarFuncionario_.setText("Funcionario");
        jMenuItem_ConsultarFuncionario_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ConsultarFuncionario_ActionPerformed(evt);
            }
        });
        jMenu1_ConsultaProduto.add(jMenuItem_ConsultarFuncionario_);

        jMenuItem_produto_.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jMenuItem_produto_.setText("Produto");
        jMenuItem_produto_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_produto_ActionPerformed(evt);
            }
        });
        jMenu1_ConsultaProduto.add(jMenuItem_produto_);

        jMenuBar1.add(jMenu1_ConsultaProduto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdp_principal)
                    .addComponent(jPanel_principal_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdp_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_principal_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_produto_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_produto_ActionPerformed
        // TODO add your handling code here:
       ProdutoV p = new ProdutoV();
        jdp_principal.add(p);
        p.setVisible(true);;
    }//GEN-LAST:event_jButton_produto_ActionPerformed

    private void jButton_comprar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_comprar_ActionPerformed
        // TODO add your handling code here:
        ComprarV c = new ComprarV();
        jdp_principal.add(c);
        c.setVisible(true);;
    }//GEN-LAST:event_jButton_comprar_ActionPerformed

    private void jButton_fechar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fechar_ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton_fechar_ActionPerformed

    private void jMenuItem_cliente_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_cliente_ActionPerformed
        // TODO add your handling code here:
        ClienteV c = new ClienteV();
        jdp_principal.add(c);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItem_cliente_ActionPerformed

    private void jMenuItem_fornecedor_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_fornecedor_ActionPerformed
        // TODO add your handling code here:
        FornecedorV f = new FornecedorV();
        jdp_principal.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem_fornecedor_ActionPerformed

    private void jMenuItem_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_funcionarioActionPerformed
        // TODO add your handling code here:
        FuncionarioV f =  new FuncionarioV();
        jdp_principal.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem_funcionarioActionPerformed

    private void jMenuItem_ConsultarCompra_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ConsultarCompra_ActionPerformed
        // TODO add your handling code here:
        ConsultarCompra c = new ConsultarCompra();
        jdp_principal.add(c);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItem_ConsultarCompra_ActionPerformed

    private void jMenuItem_CobsultarCliente_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CobsultarCliente_ActionPerformed
        // TODO add your handling code here:
        ConsultarCliente c = new ConsultarCliente();
        jdp_principal.add(c);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItem_CobsultarCliente_ActionPerformed

    private void jMenuItem_ConsultarFornecedor_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ConsultarFornecedor_ActionPerformed
        // TODO add your handling code here:
        ConsultarFornecedor f = new ConsultarFornecedor();
        jdp_principal.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem_ConsultarFornecedor_ActionPerformed

    private void jMenuItem_ConsultarFuncionario_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ConsultarFuncionario_ActionPerformed
        // TODO add your handling code here:
        ConsultarFuncionario f = new ConsultarFuncionario();
        jdp_principal.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem_ConsultarFuncionario_ActionPerformed

    private void jMenuItem_produto_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_produto_ActionPerformed
        // TODO add your handling code here:
        ConsultarProduto c = new ConsultarProduto();
        jdp_principal.add(c);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItem_produto_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_comprar_;
    private javax.swing.JButton jButton_fechar_;
    private javax.swing.JButton jButton_produto_;
    private javax.swing.JMenu jMenu1_ConsultaProduto;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_CobsultarCliente_;
    private javax.swing.JMenuItem jMenuItem_ConsultarCompra_;
    private javax.swing.JMenuItem jMenuItem_ConsultarFornecedor_;
    private javax.swing.JMenuItem jMenuItem_ConsultarFuncionario_;
    private javax.swing.JMenuItem jMenuItem_cliente_;
    private javax.swing.JMenuItem jMenuItem_fornecedor_;
    private javax.swing.JMenuItem jMenuItem_funcionario;
    private javax.swing.JMenuItem jMenuItem_produto_;
    private javax.swing.JMenu jMenu_cadastrar;
    private javax.swing.JPanel jPanel_principal_;
    private javax.swing.JDesktopPane jdp_principal;
    // End of variables declaration//GEN-END:variables
}
